## Week 5

Exercise 1

In [1]:
import numpy as np

In [2]:
arr=np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])

In [3]:
arr.reshape(5,4)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [4]:
arr[0::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

### Exercise 2

**Create a result array by adding the following two NumPy arrays. Next, modify the result
array by calculating the square of each element.**

In [6]:
arr1=np.array([[2,4,5,6],[7,8,9,12]])
arr2=np.array([[3,6,5,7],[7,8,4,7]])

In [7]:
arr3=arr1+arr2

In [8]:
arr3

array([[ 5, 10, 10, 13],
       [14, 16, 13, 19]])

In [9]:
np.square(arr3)

array([[ 25, 100, 100, 169],
       [196, 256, 169, 361]])

In [17]:
result=np.add(arr1,arr2)
result

array([[ 5, 10, 10, 13],
       [14, 16, 13, 19]])

In [15]:
np.square(result)

array([[ 25, 100, 100, 169],
       [196, 256, 169, 361]])

## Exercise 3

## Delete the second column from a given array and insert the following new column in its
## place

In [37]:
ar=np.array([[2,4,5],[7,8,9],[4,5,6]])
newar=np.array([[3,7,9]])
print("Original array:")
print(ar)
print()
ar1=ar[::,0::2]
print("Deleting second column:")
print(ar1)
print()

ar2=np.insert(ar1,1,newar,axis=1)
print("Inserting new column:")
print(ar2)
print()


Original array:
[[2 4 5]
 [7 8 9]
 [4 5 6]]

Deleting second column:
[[2 5]
 [7 9]
 [4 6]]

Inserting new column:
[[2 3 5]
 [7 7 9]
 [4 9 6]]



In [39]:
ar=np.array([[2,4,5],[7,8,9],[4,5,6]])
newar=np.array([[3,7,9]])
print("Original array:")
print(ar)
print()
ar3=np.delete(ar,1,axis=1)
print("Deleting second column:")
print(ar3)
print()
ar4=np.insert(ar3,1,newar,axis=1)
print("Inserting new column:")
print(ar4)
print()


Original array:
[[2 4 5]
 [7 8 9]
 [4 5 6]]

Deleting second column:
[[2 5]
 [7 9]
 [4 6]]

Inserting new column:
[[2 3 5]
 [7 7 9]
 [4 9 6]]




## Excercise 4

### Sort following NumPy array
**Case 1: Sort array by the second row.**

**Case 2: Sort the array by the second column.**



In [8]:
import numpy as np
ar=np.array([[34,43,73],[82,22,12],[53,94,66]])

print(ar)


sorted_array = ar[:,ar[1, :].argsort()] # Sort by the second row

print("Sorted by the second row:")
print(sorted_array)

sorted_array = ar[ar[:, 1].argsort()] # Sort by the second column

print("Sorted by the second column:")
print(sorted_array)



[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorted by the second row:
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorted by the second column:
[[82 22 12]
 [34 43 73]
 [53 94 66]]


## Exercise 5

**In the following array, negate all elements which are between 3 and 8, in place.
Z = [2 3 6 7 9 8 4 7 9 2 1 0 4]**

In [13]:
import numpy as np

Z = np.array([2, 3, 6, 7, 9, 8, 4, 7, 9, 2, 1, 0, 4])
index = np.where((Z>2) & (Z<8))
Z[index] *= -1
print(Z)

[ 2 -3 -6 -7  9  8 -4 -7  9  2  1  0 -4]
