 ## Week 6

## Exercise 1 

* Question a

## Generate a 10 x 3 array of random numbers (in range [0,1])

In [1]:
import numpy as np

In [6]:
x=np.random.rand(10,3)
print(x)

[[0.90730658 0.597464   0.45766869]
 [0.87629888 0.36250432 0.12996004]
 [0.71142544 0.53413201 0.29629219]
 [0.95720179 0.6616406  0.0084852 ]
 [0.24332746 0.40955234 0.9356977 ]
 [0.49350768 0.77668851 0.31875325]
 [0.71447093 0.96983696 0.7452767 ]
 [0.32041974 0.53697114 0.93709155]
 [0.44268277 0.54998181 0.68029052]
 [0.2445674  0.82261844 0.61171595]]


 ## Each element, compute the distance to 0.5

In [20]:
distance=np.abs(x-0.5) # Used abs function to avoid negative sign
print("Distance between each element to 0.5", distance)


Distance between each element to 0.5 [[0.40730658 0.097464   0.04233131]
 [0.37629888 0.13749568 0.37003996]
 [0.21142544 0.03413201 0.20370781]
 [0.45720179 0.1616406  0.4915148 ]
 [0.25667254 0.09044766 0.4356977 ]
 [0.00649232 0.27668851 0.18124675]
 [0.21447093 0.46983696 0.2452767 ]
 [0.17958026 0.03697114 0.43709155]
 [0.05731723 0.04998181 0.18029052]
 [0.2554326  0.32261844 0.11171595]]


## Return the indices that would sort an array (closest to farthest from 0.5 – horizontally)

In [24]:
sortes_array=np.argsort(distance, axis=1)
print(sortes_array)

[[2 1 0]
 [1 2 0]
 [1 2 0]
 [1 0 2]
 [1 0 2]
 [0 2 1]
 [0 2 1]
 [1 0 2]
 [1 0 2]
 [2 0 1]]


## For each row, we are only interested in the column that is closest to 0.5 so get rid of the
## other 2 numbers in each row. You will end up with an array of 10 elements. (Numbers are
## element positions)

In [30]:
closest_indices=sortes_array[:,0]


 Indices of a Column that is closest to 0.5 avoiding two other numbers [2 1 1 1 1 0 0 1 1 2]


In [32]:
[x[i][closest_indices[i]] for i in range(x.shape[0])]


[0.4576686854030091,
 0.3625043172868677,
 0.5341320077355297,
 0.6616405987809346,
 0.40955234175293664,
 0.4935076761874784,
 0.7144709285931532,
 0.5369711406064185,
 0.5499818091281466,
 0.611715947917132]

## For each row, extract the element value that is closest to 0.5

In [33]:
[x[i][closest_indices[i]] for i in range(x.shape[1])]

[0.4576686854030091, 0.3625043172868677, 0.5341320077355297]

## Exercise 2

## From the array [5,4,6,10,24,89,45,43,46,99,100]extract all the numbers

# 1. which are not divisible by 3

In [42]:
y= np.array([5,4,6,10,24,89,45,43,46,99,100])
dv=y[y%3!=0]
print("Numbers which are not divisible by 3:",dv)


Numbers which are not divisible by 3: [  5   4  10  89  43  46 100]


 # 2.which are divisible by 5

In [43]:
y= np.array([5,4,6,10,24,89,45,43,46,99,100])
dv=y[y%5==0]
print("Numbers which are divisible by 5:",dv)

Numbers which are divisible by 5: [  5  10  45 100]


# 3.which are divisible by 3 and 5

In [51]:
y= np.array([5,4,6,10,24,89,45,43,46,99,100])
dv=y[(y%3==0) & (y%5==0)]
print("Numbers which are divisible by 3and 5:",dv)


Numbers which are divisible by 3and 5: [45]


# 4.which are divisible by 3 and set them to 42

In [58]:
y= np.array([5,4,6,10,24,89,45,43,46,99,100])
dv=y[y%3==0]
print("Numbers which are  divisible by 3:",dv)

Numbers which are  divisible by 3: [ 6 24 45 99]


### Exercise 3

***Calculate the prime numbers between 0 and 100 by using a Boolean array.
Calculate the first 100 prime numbers***

In [1]:
import numpy as np

is_prime = np.ones((100,), dtype=bool)

# Cross out 0 and 1 which are not primes:
is_prime[:2] = 0

# cross out its higher multiples (sieve of Eratosthenes):
nmax = int(np.sqrt(len(is_prime)))
for i in range(2, nmax):
    is_prime[2*i::i] = False

print(np.nonzero(is_prime))

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int64),)
